#dbt_project.yml

name: 'przetwarzanie_elt'
version: '1.0.0'
config-version: 2

profile: 'przetwarzanie_elt'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  przetwarzanie_elt:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +materialized: table
      +schema: marts

seeds:
  przetwarzanie_elt:
    +schema: staging
    +materialized: seed
